server:
  port: 8001

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://116.62.8.243:13306/api_gateway?useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  config-location: classpath:/config/mybatis-config.xml