server:
  port: 8001

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/api_gateway?useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      initialSize: 5
      minIdle: 10
      maxActive: 1000
      #配置获取连接等待超时的时间
      maxWait: 5000
      #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 30000
      #配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1
      #指明连接是否被空闲连接回收器(如果有)进行检验.如果检测失败,则连接将被从池中去除.
      testWhileIdle: true
      #指明是否在从池中取出连接前进行检验,如果检验失败,则从池中去除连接并尝试取出另一个
      testOnBorrow: true
      #指明是否在归还到池中前进行检验
      testOnReturn: false
  redis:
    host: 127.0.0.1
    port: 6379

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  config-location: classpath:/config/mybatis-config.xml

